### ISSUE TITLE
Doubt 

### ISSUE THREAD

**Issue by LuisValgoi** [rahulinamdar/UI5-WebComponents#1]
https://github.com/rahulinamdar/UI5-WebComponents/blob/49fb6aac3ef0a4dfea9a50ef7370d033ba5eb5af/src/index.html#L11

Hey, nice to meet you!

I was looking at this code and I was wondering what is this tag for?

Tks!

**Comment by rahulinamdar** [comment]
Hi,

That tag is useful for configuring themes, language or any global config
required to bootstrap the UI5 we components.

Quite similar tag used in bootstrapping of UI5 framework in UI5 application.

Thanka

**Comment by LuisValgoi** [comment]
Oh, sure!
Thanks.
I'm new on WebComponents and I was wondering how can I improve my skills.
Do you have any video/course suggestion?

**Comment by rahulinamdar** [comment]
https://sap.github.io/ui5-webcomponents/
